name: Deploy to Hetzner

on:
  push:
    branches: ["**"]

jobs:
  web-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          cache: 'yarn'

      - name: Install packages
        run: yarn

      - name: Build project
        run: yarn build

      - name: Sync files
        if: github.ref_name == 'main'
        uses: swillner/sftp-sync-action@v1.0
        with:
          server: "${{ secrets.SERVER }}"
          user: "${{ secrets.USER }}"
          user_private_key: "${{ secrets.SSH_PRIVATE_KEY }}"
          host_public_key: |-
            -----BEGIN CERTIFICATE-----
            MIIHGjCCBgKgAwIBAgIQC2vBNnfdHPYQHmfirrWNETANBgkqhkiG9w0BAQsFADBe
            MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQLExB3
            d3cuZGlnaWNlcnQuY29tMR0wGwYDVQQDExRUaGF3dGUgVExTIFJTQSBDQSBHMTAe
            Fw0yNTEwMTAwMDAwMDBaFw0yNjExMDIyMzU5NTlaMBsxGTAXBgNVBAMMECoueW91
            ci1zZXJ2ZXIuZGUwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQCS82hJ
            yvb1TLVq3iQdqwIsFC/d5oBn/RDslTwaOhg+y+5ynQRe0BHljn5BcGrnybKrE41g
            cuZBr1kzaXBxHEMSonFSlYXF5mC53MmGy20JSrokTco5+unksizNrcxNzwPXu4zG
            SAHdJTa6RkemO3KIMoCJQoY1+ppsfN4KXzLDKEJL3z3rKNOap5kpuYb3UtW5wbsu
            9n8AD5jn5rSuKX+7KoJNLYl9a0DX12pwMRTUwo3j3+FYz4SUHG0BOhWmlxeLzNne
            lVw9h6rlaB5Tqjcf/i6RyQCPxGTd0gdGMMqJNYScMgl1pAQwRF2LHjYvbTqbB8xg
            /Y8bi4YDXVW6S7wNi3PhjgkbxpOyM6P9w3mICrs39ArQWuE/2hJnwk2rqfQVAIx+
            Q3jpbGDhdwrdXARTIeee9zCGC/7OmZE2JpzKGwmzWBlQm4kxhsq1kMFWnBsoPsWb
            2a8bdrBgHSYGHx8c2fuCngkcclA1GDkDC+iWjqovd2XEIzxlRgFRhsXt1cSzfN/P
            HsPvcy/Wtrt+b6q8xjYX2A+LN4W3Z7mqaRqOm4YsFxbOAIJKl7zIhbquRwbbeToX
            H3YxL1TGZI2qqX3qXrjsKZSCK94ZxEb7hYRVutAv66S0GH91iogI0aXnN4gnQ8aR
            RfMyv2nchN92WEh27PQCSe0hWfOI4hF6p9lsfQIDAQABo4IDFTCCAxEwHwYDVR0j
            BBgwFoAUpYz+MszrDyzUGcYIuAAkiF3DxbcwHQYDVR0OBBYEFKT8a7auZFyxNyoy
            1/mLhOv8goF8MCsGA1UdEQQkMCKCECoueW91ci1zZXJ2ZXIuZGWCDnlvdXItc2Vy
            dmVyLmRlMD4GA1UdIAQ3MDUwMwYGZ4EMAQIBMCkwJwYIKwYBBQUHAgEWG2h0dHA6
            Ly93d3cuZGlnaWNlcnQuY29tL0NQUzAOBgNVHQ8BAf8EBAMCBaAwEwYDVR0lBAww
            CgYIKwYBBQUHAwEwOwYDVR0fBDQwMjAwoC6gLIYqaHR0cDovL2NkcC50aGF3dGUu
            Y29tL1RoYXd0ZVRMU1JTQUNBRzEuY3JsMHAGCCsGAQUFBwEBBGQwYjAkBggrBgEF
            BQcwAYYYaHR0cDovL3N0YXR1cy50aGF3dGUuY29tMDoGCCsGAQUFBzAChi5odHRw
            Oi8vY2FjZXJ0cy50aGF3dGUuY29tL1RoYXd0ZVRMU1JTQUNBRzEuY3J0MAwGA1Ud
            EwEB/wQCMAAwggF+BgorBgEEAdZ5AgQCBIIBbgSCAWoBaAB3ANdtfRDRp/V3wsfp
            X9cAv/mCyTNaZeHQswFzF8DIxWl3AAABmc0GD/oAAAQDAEgwRgIhAKsZ7ukRPlQo
            p0My7z3yeljL4/JKSijyqHjGaG6DN/YyAiEAptUaEa1zd+d3q8+rHiWNdlV4dhGs
            LoRkN9KvXviRiLQAdgDCMX5XRRmjRe5/ON6ykEHrx8IhWiK/f9W1rXaa2Q5SzQAA
            AZnNBhAnAAAEAwBHMEUCIDEs9JPRZiK4zEzRPlVG4S5yKkaD4yRyBKYBFlXJg3se
            AiEA39HJkjCFBneLsf0FG0KV11dCU1ZGV0qXTDv3//Vo6KgAdQCUTkOH+uzB74Hz
            GSQmqBhlAcfTXzgCAT9yZ31VNy4Z2AAAAZnNBhA9AAAEAwBGMEQCIDwL0fPRR2ni
            OdzzzcYzYjZOTnovMpdHuBjYnBiT7HKcAiARWUjouXXvs2IozPzVRd+meVirtApr
            /bPjm/NlGJa+WDANBgkqhkiG9w0BAQsFAAOCAQEALyhuc+HkPvoq8YblM4lRj8wT
            C6vkaXPUmwCxC0Vnlb7U4X0bhhXh8B4YVrcgjOuFRSPo/FjwFAxAUfNHqSYF2f7Y
            sapzMWz9xSH2YKxuTkIZaVHyPlrazG5h03j655GecbYrcbzwSTFw6ObT9At3yAwP
            BFnjVkSfLo1HPJJmzbFomVQbnND1hmESuh2x2oFuSrnbuD4jSNWBAWKAzm9fsHDQ
            JPUzztqhdS8K8ulutiQwpDpT5Ci3oOLlkRj4mk4W6DOG7KjMu48Pdta7AUxjaIuS
            Lx2jv/XKWqqUpkeP9kJp1h3N4sU6AbOjct/NT3+ljNyov8hB4MjFed//qDElOg==
            -----END CERTIFICATE-----
          remote: "public_html/homepage/"
          local: "dist/"
          mirror_options: "--exclude-glob=.git*/ --dry-run --delete"
