name: Deploy to Hetzner

on:
  push:
    branches: ["**"]

jobs:
  web-deploy:
    if: false
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install packages
        run: yarn

      - name: Build project
        run: yarn build

      - name: Sync files
        if: github.ref_name == 'main'
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: "${{ secrets.USERNAME }}"
          server: "${{ secrets.SERVER }}"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: "./dist/*"
          remote_path: "public_html/"
          sftp_only: true
