name: Deploy to VPS

on:
  push:
    branches: ["**"]

jobs:
  web-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install packages
        run: yarn

      - name: Build project
        run: yarn build

      - name: Sync files (dry-run)
        if: github.ref_name != 'main'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.server }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          local-dir: dist/
          server-dir: public_html/
          dry-run: true

      - name: Sync files
        if: github.ref_name == 'main'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.server }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          local-dir: dist/
          server-dir: public_html/
          dry-run: false
