name: Deploy to VPS

on:
  push:
    branches: [main]

env:
  REMOTE_HOST: ${{ secrets.VPS_HOST }}
  REMOTE_USER: ${{ secrets.VPS_USERNAME }}
  SSH_PRIVATE_KEY: ${{ secrets.VPS_KEY }}
  SOURCE: dist/
  TARGET: /var/www/html/

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install packages
        run: yarn

      - name: Build project
        run: yarn build

      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v4.1.8
